[package]
name = "host"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.7"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.48.0", features = ["macros", "rt"] }
wasmtime = "39.0.1"
wasmtime-wasi = "39.0.1"
